name: CI Pipeline - Fullstack App

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # === BACKEND ===
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        run: npm test

      # === FRONTEND ===
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Test frontend
        working-directory: frontend
        run: npm run test || echo "Pas de tests frontend pour le moment"

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: ✅ Ready to deploy
        run: echo "Le build et les tests sont terminés. Prêt à déployer !"
