name: Audit de Securite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Execution automatique chaque lundi a 9h
    - cron: '0 9 * * 1'

env:
  NODE_VERSION: '20'

jobs:
  audit-dependencies:
    name: Audit des Dependances
    runs-on: ubuntu-latest
    
    steps:
    - name: Recuperation du code
      uses: actions/checkout@v4
      
    - name: Configuration Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Audit backend
      working-directory: ./backend
      run: |
        npm ci
        npm audit --audit-level moderate

    - name: Audit frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm audit --audit-level moderate
